//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirabeau.uTransporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Namespaces : global::System.Configuration.ApplicationSettingsBase {
        
        private static Namespaces defaultInstance = ((Namespaces)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Namespaces())));
        
        public static Namespaces Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mirabeau.uTransporter.Attributes")]
        public string AttributesNamespace {
            get {
                return ((string)(this["AttributesNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mirabeau.uTransporter.Enums")]
        public string EnumsNamespace {
            get {
                return ((string)(this["EnumsNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mirabeau.uTransporter.Models")]
        public string ModelsNamespace {
            get {
                return ((string)(this["ModelsNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System ")]
        public string SystemNamespace {
            get {
                return ((string)(this["SystemNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uTransporter.DocumentTypes")]
        public string DocumentTypeNamespace {
            get {
                return ((string)(this["DocumentTypeNamespace"]));
            }
        }
    }
}
