//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Enums;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Contact", Alias="Contact", Icon=".sprTreeNewsletter", Thumbnail="folder.png", Description="", AllowAtRoot=false, DefaultTemplate=typeof(Templates.Contact), AllowedTemplates=new System.Type[] {
            typeof(Templates.Contact)}, AllowedChildNodeTypes=new System.Type[0])]
    public class Contact : Master
    {
        
        private string _Titel;
        
        private string _Tekst;
        
        private string _Foto;
        
        private string _NaamRecruiter;
        
        private string _Functietitel;
        
        private string _Telefoon;
        
        private string _Email;
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Titel", Alias="titel", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Titel
        {
            get
            {
                return this._Titel;
            }
            set
            {
                this._Titel = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.TinyMCEv3, Name="Tekst", Alias="tekst", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Tekst
        {
            get
            {
                return this._Tekst;
            }
            set
            {
                this._Tekst = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.MediaPicker, Name="Foto", Alias="foto", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Foto
        {
            get
            {
                return this._Foto;
            }
            set
            {
                this._Foto = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Naam Recruiter", Alias="naamRecruiter", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string NaamRecruiter
        {
            get
            {
                return this._NaamRecruiter;
            }
            set
            {
                this._NaamRecruiter = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Functietitel", Alias="functieTitel", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Functietitel
        {
            get
            {
                return this._Functietitel;
            }
            set
            {
                this._Functietitel = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Telefoon", Alias="telefoon", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Telefoon
        {
            get
            {
                return this._Telefoon;
            }
            set
            {
                this._Telefoon = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Email", Alias="email", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this._Email = value;
            }
        }
    }
}
