//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Enums;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Content", Alias="Content", Icon="page_white_text.png", Thumbnail="doc.png", Description="", AllowAtRoot=false, DefaultTemplate=typeof(Templates.ContentPage), AllowedTemplates=new System.Type[] {
            typeof(Templates.ContentPage),
            typeof(Templates.VacatureOverzicht),
            typeof(Templates.VacatureDetail)}, AllowedChildNodeTypes=new System.Type[] {
            typeof(DocumentTypes.Vestiging),
            typeof(DocumentTypes.Content)})]
    public class Content : Master
    {
        
        private string _Titel;
        
        private string _Tekst;
        
        private string _Link;
        
        private string _SubTitle;
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Titel", Alias="titel", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Titel
        {
            get
            {
                return this._Titel;
            }
            set
            {
                this._Titel = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.TinyMCEv3, Name="Tekst", Alias="tekst", Description="", Tab=typeof(Tabs.Content), SortOrder=2, Mandatory=false, ValidationRegExp="")]
        public string Tekst
        {
            get
            {
                return this._Tekst;
            }
            set
            {
                this._Tekst = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MIRA:SingleLink", Name="Link", Alias="link", Description="", Tab=typeof(Tabs.Content), SortOrder=3, Mandatory=false, ValidationRegExp="")]
        public string Link
        {
            get
            {
                return this._Link;
            }
            set
            {
                this._Link = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="SubTitle", Alias="subTitle", Description="", Tab=typeof(Tabs.Content), SortOrder=1, Mandatory=false, ValidationRegExp="")]
        public string SubTitle
        {
            get
            {
                return this._SubTitle;
            }
            set
            {
                this._SubTitle = value;
            }
        }
    }
}
