//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Models;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Data", Alias="Data", Icon=".sprTreeRepository", Thumbnail="folder.png", Description="", AllowAtRoot=true, AllowedTemplates=new System.Type[0], AllowedChildNodeTypes=new System.Type[] {
            typeof(DocumentTypes.QuoteBlokContainer),
            typeof(DocumentTypes.Settings),
            typeof(DocumentTypes.VacatureContainer),
            typeof(DocumentTypes.Tags)})]
    public class Data : IDocumentTypeBase
    {
    }
}
