//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Enums;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Portfolio", Alias="Portfolio", Icon="page_white_stack.png", Thumbnail="folder.png", Description="", AllowAtRoot=false, DefaultTemplate=typeof(Templates.PortFolioPage), AllowedTemplates=new System.Type[] {
            typeof(Templates.PortFolioPage)}, AllowedChildNodeTypes=new System.Type[0])]
    public class Portfolio : Master
    {
        
        private string _Titel;
        
        private string _ExternPortfolio;
        
        private string _Tekst;
        
        private string _PortfolioItems;
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Titel", Alias="titel", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Titel
        {
            get
            {
                return this._Titel;
            }
            set
            {
                this._Titel = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MIRA:SingleLink", Name="Extern Portfolio", Alias="externPortfolio", Description="", Tab=typeof(Tabs.Content), SortOrder=2, Mandatory=false, ValidationRegExp="")]
        public string ExternPortfolio
        {
            get
            {
                return this._ExternPortfolio;
            }
            set
            {
                this._ExternPortfolio = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.TinyMCEv3, Name="Tekst", Alias="tekst", Description="", Tab=typeof(Tabs.Content), SortOrder=1, Mandatory=false, ValidationRegExp="")]
        public string Tekst
        {
            get
            {
                return this._Tekst;
            }
            set
            {
                this._Tekst = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.ContentPicker, Name="Portfolio Items", Alias="portfolioItems", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string PortfolioItems
        {
            get
            {
                return this._PortfolioItems;
            }
            set
            {
                this._PortfolioItems = value;
            }
        }
    }
}
