//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Enums;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Quote Blok", Alias="QuoteBlok", Icon="settingCss.gif", Thumbnail="folder.png", Description="", AllowAtRoot=false, AllowedTemplates=new System.Type[0], AllowedChildNodeTypes=new System.Type[0])]
    public class QuoteBlok : Data
    {
        
        private string _QuoteTekst;
        
        private string _KleineTekstOnderQuote;
        
        private string _Foto;
        
        private string _TekstOnderFoto;
        
        private string _Link;
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Quote Tekst", Alias="quoteTekst", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string QuoteTekst
        {
            get
            {
                return this._QuoteTekst;
            }
            set
            {
                this._QuoteTekst = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Kleine tekst onder Quote", Alias="kleineTekstOnderQuote", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string KleineTekstOnderQuote
        {
            get
            {
                return this._KleineTekstOnderQuote;
            }
            set
            {
                this._KleineTekstOnderQuote = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.MediaPicker, Name="Foto", Alias="foto", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Foto
        {
            get
            {
                return this._Foto;
            }
            set
            {
                this._Foto = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.SimpleEditor, Name="Tekst onder foto", Alias="tekstOnderFoto", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string TekstOnderFoto
        {
            get
            {
                return this._TekstOnderFoto;
            }
            set
            {
                this._TekstOnderFoto = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MIRA:SingleLink", Name="Link", Alias="link", Description="", Tab=typeof(Tabs.Content), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Link
        {
            get
            {
                return this._Link;
            }
            set
            {
                this._Link = value;
            }
        }
    }
}
