//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Enums;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Settings", Alias="Settings", Icon=".sprTreeDeveloperMacro", Thumbnail="folder.png", Description="", AllowAtRoot=false, AllowedTemplates=new System.Type[0], AllowedChildNodeTypes=new System.Type[0])]
    public class Settings : Data
    {
        
        private string _HeaderLinks;
        
        private string _FooterLinks;
        
        private string _VirtualTour;
        
        private string _VacatureSuccesPagina;
        
        private string _VacatureErrorPagina;
        
        private string _LocationFilter;
        
        private string _VakgebiedFilter;
        
        private string _ErvaringFilter;
        
        private string _AantalVacaturesPerPagina;
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MultiLinkPicker", Name="HeaderLinks", Alias="headerLinks", Description="", Tab=typeof(Tabs.Instellingen), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string HeaderLinks
        {
            get
            {
                return this._HeaderLinks;
            }
            set
            {
                this._HeaderLinks = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MultiLinkPicker", Name="FooterLinks", Alias="footerLinks", Description="", Tab=typeof(Tabs.Instellingen), SortOrder=1, Mandatory=false, ValidationRegExp="")]
        public string FooterLinks
        {
            get
            {
                return this._FooterLinks;
            }
            set
            {
                this._FooterLinks = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.MediaPicker, Name="Virtual Tour", Alias="virtualTour", Description="", Tab=typeof(Tabs.Instellingen), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string VirtualTour
        {
            get
            {
                return this._VirtualTour;
            }
            set
            {
                this._VirtualTour = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.ContentPicker, Name="Vacature Succes Pagina", Alias="vacatureSuccesPagina", Description="", Tab=typeof(Tabs.Instellingen), SortOrder=0, Mandatory=true, ValidationRegExp="")]
        public string VacatureSuccesPagina
        {
            get
            {
                return this._VacatureSuccesPagina;
            }
            set
            {
                this._VacatureSuccesPagina = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.ContentPicker, Name="Vacature Error Pagina", Alias="vacatureErrorPagina", Description="", Tab=typeof(Tabs.Instellingen), SortOrder=0, Mandatory=true, ValidationRegExp="")]
        public string VacatureErrorPagina
        {
            get
            {
                return this._VacatureErrorPagina;
            }
            set
            {
                this._VacatureErrorPagina = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.ContentPicker, Name="LocationFilter", Alias="locationFilter", Description="", Tab=typeof(Tabs.SearchSettings), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string LocationFilter
        {
            get
            {
                return this._LocationFilter;
            }
            set
            {
                this._LocationFilter = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.ContentPicker, Name="VakgebiedFilter", Alias="vakgebiedFilter", Description="", Tab=typeof(Tabs.SearchSettings), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string VakgebiedFilter
        {
            get
            {
                return this._VakgebiedFilter;
            }
            set
            {
                this._VakgebiedFilter = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.ContentPicker, Name="ErvaringFilter", Alias="ervaringFilter", Description="", Tab=typeof(Tabs.SearchSettings), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string ErvaringFilter
        {
            get
            {
                return this._ErvaringFilter;
            }
            set
            {
                this._ErvaringFilter = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Numeric, Name="Aantal vacatures per pagina", Alias="aantalVacaturesPerPagina", Description="", Tab=typeof(Tabs.SearchSettings), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string AantalVacaturesPerPagina
        {
            get
            {
                return this._AantalVacaturesPerPagina;
            }
            set
            {
                this._AantalVacaturesPerPagina = value;
            }
        }
    }
}
