//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Tags", Alias="Tags", Icon="folder.gif", Thumbnail="folder.png", Description="", AllowAtRoot=false, AllowedTemplates=new System.Type[0], AllowedChildNodeTypes=new System.Type[] {
            typeof(DocumentTypes.Tags),
            typeof(DocumentTypes.Tag)})]
    public class Tags : Data
    {
    }
}
