//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Enums;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Vacature", Alias="Vacature", Icon="doc.gif", Thumbnail="folder.png", Description="", AllowAtRoot=false, DefaultTemplate=typeof(Templates.VacatureDetail), AllowedTemplates=new System.Type[] {
            typeof(Templates.VacatureDetail)}, AllowedChildNodeTypes=new System.Type[0])]
    public class Vacature : Data
    {
        
        private string _CatsId;
        
        private string _Functie;
        
        private string _FunctieProfiel;
        
        private string _CarriereNiveau;
        
        private string _Vestigingen;
        
        private string _Vakgebied;
        
        private string _DisplayOnHomepage;
        
        private string _SoortVacature;
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="CatsId", Alias="catsId", Description="", SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string CatsId
        {
            get
            {
                return this._CatsId;
            }
            set
            {
                this._CatsId = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Functie", Alias="functie", Description="", Tab=typeof(Tabs.VacatureInformatie), SortOrder=0, Mandatory=true, ValidationRegExp="")]
        public string Functie
        {
            get
            {
                return this._Functie;
            }
            set
            {
                this._Functie = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.TinyMCEv3, Name="Functie profiel", Alias="functieProfiel", Description="", Tab=typeof(Tabs.VacatureInformatie), SortOrder=1, Mandatory=false, ValidationRegExp="")]
        public string FunctieProfiel
        {
            get
            {
                return this._FunctieProfiel;
            }
            set
            {
                this._FunctieProfiel = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MIRA:CarriereNiveau", Name="CarriereNiveau", Alias="carriereNiveau", Description="", Tab=typeof(Tabs.VacatureInformatie), SortOrder=2, Mandatory=false, ValidationRegExp="")]
        public string CarriereNiveau
        {
            get
            {
                return this._CarriereNiveau;
            }
            set
            {
                this._CarriereNiveau = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MIRA:VestigingPicker", Name="Vestigingen", Alias="vestigingen", Description="", Tab=typeof(Tabs.VacatureInformatie), SortOrder=5, Mandatory=false, ValidationRegExp="")]
        public string Vestigingen
        {
            get
            {
                return this._Vestigingen;
            }
            set
            {
                this._Vestigingen = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Other, OtherTypeName="MIRA:Vakgebied", Name="Vakgebied", Alias="vakgebied", Description="", Tab=typeof(Tabs.VacatureInformatie), SortOrder=4, Mandatory=false, ValidationRegExp="")]
        public string Vakgebied
        {
            get
            {
                return this._Vakgebied;
            }
            set
            {
                this._Vakgebied = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Display on Homepage", Alias="displayOnHomepage", Description="", Tab=typeof(Tabs.VacatureInformatie), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string DisplayOnHomepage
        {
            get
            {
                return this._DisplayOnHomepage;
            }
            set
            {
                this._DisplayOnHomepage = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Soort vacature", Alias="soortVacature", Description="", Tab=typeof(Tabs.VacatureInformatie), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string SoortVacature
        {
            get
            {
                return this._SoortVacature;
            }
            set
            {
                this._SoortVacature = value;
            }
        }
    }
}
