//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Vacatures Overzicht", Alias="VacaturesOverzicht", Icon="zoom.png", Thumbnail="folder.png", Description="", AllowAtRoot=false, DefaultTemplate=typeof(Templates.VacatureOverzicht), AllowedTemplates=new System.Type[] {
            typeof(Templates.VacatureOverzicht)}, AllowedChildNodeTypes=new System.Type[] {
            typeof(DocumentTypes.Vacature)})]
    public class VacaturesOverzicht : Master
    {
    }
}
