//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Mirabeau.uTransporter.Attributes;
using Mirabeau.uTransporter.Enums;

namespace Mirabeau.uTransporter.UnitTests.Stubs.DocumentTypes
{
    [DocumentType(Name="Vestiging", Alias="Vestiging", Icon=".sprTreemediaFile", Thumbnail="folder.png", Description="", AllowAtRoot=false, DefaultTemplate=typeof(Templates.Vestiging), AllowedTemplates=new System.Type[] {
            typeof(Templates.Vestiging)}, AllowedChildNodeTypes=new System.Type[0])]
    public class Vestiging : Master
    {
        
        private string _Fotos;
        
        private string _RouteAuto;
        
        private string _RouteOV;
        
        private string _Lokatie;
        
        private string _SubTitle;
        
        private string _Tekst;
        
        private string _Adres;
        
        private string _Telefoon;
        
        private string _Omschrijving;
        
        [DocumentTypeProperty(UmbracoPropertyType.MediaPicker, Name="Fotos", Alias="fotos", Description="", Tab=typeof(Tabs.Fotos), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Fotos
        {
            get
            {
                return this._Fotos;
            }
            set
            {
                this._Fotos = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.TinyMCEv3, Name="Route Auto", Alias="routeAuto", Description="", Tab=typeof(Tabs.Auto), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string RouteAuto
        {
            get
            {
                return this._RouteAuto;
            }
            set
            {
                this._RouteAuto = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.TinyMCEv3, Name="Route OV", Alias="routeOV", Description="", Tab=typeof(Tabs.OV), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string RouteOV
        {
            get
            {
                return this._RouteOV;
            }
            set
            {
                this._RouteOV = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Lokatie", Alias="lokatie", Description="", Tab=typeof(Tabs.Kaart), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Lokatie
        {
            get
            {
                return this._Lokatie;
            }
            set
            {
                this._Lokatie = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="SubTitle", Alias="subTitle", Description="", Tab=typeof(Tabs.Omschrijving), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string SubTitle
        {
            get
            {
                return this._SubTitle;
            }
            set
            {
                this._SubTitle = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.TinyMCEv3, Name="Tekst", Alias="tekst", Description="", Tab=typeof(Tabs.Omschrijving), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Tekst
        {
            get
            {
                return this._Tekst;
            }
            set
            {
                this._Tekst = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Adres", Alias="adres", Description="", Tab=typeof(Tabs.Contact), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Adres
        {
            get
            {
                return this._Adres;
            }
            set
            {
                this._Adres = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Telefoon", Alias="telefoon", Description="", Tab=typeof(Tabs.Contact), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Telefoon
        {
            get
            {
                return this._Telefoon;
            }
            set
            {
                this._Telefoon = value;
            }
        }
        
        [DocumentTypeProperty(UmbracoPropertyType.Textstring, Name="Omschrijving", Alias="omschrijving", Description="", Tab=typeof(Tabs.Contact), SortOrder=0, Mandatory=false, ValidationRegExp="")]
        public string Omschrijving
        {
            get
            {
                return this._Omschrijving;
            }
            set
            {
                this._Omschrijving = value;
            }
        }
    }
}
